### ISSUE TITLE
Error: hyperv-iso: Error shutting down VM: PowerShell error: Hyper-V\Stop-VM : Failed to stop.

### ISSUE THREAD

**Issue by muthurd** [marcinbojko/hv-packer#1]
Added the post-processor to your JSON to export the hyper-v vhdx, but now getting the below error message, Would you please help.

    hyperv-iso: WINDOWS-2016V7 restarted.
    hyperv-iso: #< CLIXML
    hyperv-iso: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObje
ct</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR>
<SD> </SD></PR></MS></Obj></Objs>
==> hyperv-iso: Machine successfully restarted, moving on
==> hyperv-iso: Provisioning with Powershell...
==> hyperv-iso: Provisioning with powershell script: ./extra/scripts/windows-updates.ps1
==> hyperv-iso: Disconnecting from vmconnect...
==> hyperv-iso: Error shutting down VM: PowerShell error: Hyper-V\Stop-VM : Failed to stop.
==> hyperv-iso: At C:\Users\Administrator\AppData\Local\Temp\2\ps320263257.ps1:5 char:5
==> hyperv-iso: +     Hyper-V\Stop-VM -VM $vm -Force -Confirm:$false
==> hyperv-iso: +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> hyperv-iso:     + CategoryInfo          : NotSpecified: (:) [Stop-VM], VirtualizationException
==> hyperv-iso:     + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.StopVM
==> hyperv-iso: Clean up secondary dvd drives...
==> hyperv-iso: Clean up os dvd drive...
==> hyperv-iso: Unregistering and deleting virtual machine...
==> hyperv-iso: Deleting output directory...
==> hyperv-iso: Deleting build directory...
Build 'hyperv-iso' errored: Script exited with non-zero exit status: 2147943515. Allowed exit codes are: [0]

==> Some builds didn't complete successfully and had errors:
--> hyperv-iso: Script exited with non-zero exit status: 2147943515. Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.

**Comment by marcinbojko** [comment]
Hi.Which version of packer are you using?
Platform?

**Comment by muthurd** [comment]
I am using packer --version 1.3.1,
Installed on Windows 2016 Datacenter Server with Hyper-V installed.

**Comment by marcinbojko** [comment]
Then you should definitely read README.md, line 5 and line 181 ;)

**Comment by muthurd** [comment]
Thanks!!!, 
Line 5 says, * packer >= `1.2.3`, However I am using 1.3.1
And there are only 174 line on the README file. Please help

**Comment by marcinbojko** [comment]
Make sure you're on version 1.0.5 which was released yesterday.
![image](https://user-images.githubusercontent.com/4726723/46465739-aaa39000-c7c9-11e8-8a88-73e026e0c8fb.png)

**Comment by muthurd** [comment]
Oh ok, I understood. Thanks for checking on this.
I will try with the suggested version and let you know.
Thanks again for checking on this!!!!

**Comment by marcinbojko** [comment]
That's not a problem. I can suggest - go to that link, and get 1.3.2-dev version which SHOULD work. Thank you for contribution.

**Comment by marcinbojko** [comment]
Version 1.3.3 works perfectly.
