### ISSUE TITLE
disk space

### ISSUE THREAD

**Issue by FlorianHeigl** [marcinbojko/hv-packer#10]
Hi,

could you document how much disk space you allocated for the (gitlab-)CI builds?

I just know my normal builder will never fit all those images, but don't know how big the new one should become ;-)

**Comment by FlorianHeigl** [comment]
oh - i just figured out that the ci jobs only run a validate.

please disregard!

**Comment by marcinbojko** [comment]
Even if you'll run regular, not validate jobs, every Linux image takes approx 3-6 GB, and windows approx 15-16.
You have to double this for compacting phase.
