### ISSUE TITLE
I fail to override variable values

### ISSUE THREAD

**Issue by HackerBaloo** [marcinbojko/hv-packer#13]
I don't know if I miss something obvious, but when I try:
`.\hv_ubuntu2204.ps1 -var 'output_directory=test'`
I still get the default, "output-ubuntu2204" from 
`variables_ubuntu2204.pkvars.hcl `.

**Comment by marcinbojko** [comment]
Hi @HackerBaloo 
It's simply because script is not intended to run this way

```
# Variables
$template_file="./templates/hv_ubuntu2004_g2.pkr.hcl"
$var_file="./variables/variables_ubuntu2004.pkvars.hcl"
$machine="Ubuntu 20.04"
$packer_log=0
```

in a 'var_file" variable you have to have sets of variables.
You can edit this fle, or simply run these manually :
```
    packer build --force -var-file="$var_file" "$template_file"
```

Reworking script to accept and override default parameters seems not a bad idea though :)

**Comment by HackerBaloo** [comment]
OK, the readme mentioned -var.

**Comment by marcinbojko** [comment]
True, I see that now, I'll do the proper changes. Thanks for noticing

**Comment by marcinbojko** [comment]
Fixed by https://github.com/marcinbojko/hv-packer/commit/20a74f9e58871ef790ed8eeb49e99ec5ea2eb5d1
