### ISSUE TITLE
I get a warning and it says that source code is not available

### ISSUE THREAD

**Issue by HackerBaloo** [marcinbojko/hv-packer#14]
I get the warning below. But I run the script from the root of the repository, what source code is not available?
```
Building: Ubuntu 22.04
Warning: Hyper-V might fail to create a VM if there is not enough free memory in the system.

  on ./templates/hv_ubuntu2204_g2.pkr.hcl line 95:
  (source code not available)


The configuration is valid.
```

**Comment by marcinbojko** [comment]
This is packer's warning about not setting MEM. It's the internal message - ONLY a warning. As you can see config is valid.

**Comment by HackerBaloo** [comment]
OK, but do you also get that the source code is not available?
