### ISSUE TITLE
Ubuntu 22.04.1 Not able to Install

### ISSUE THREAD

**Issue by navanshu** [marcinbojko/hv-packer#15]
I am trying to build the latest ubuntu server using hyper-v on windows 11 machine, but the process is stuck at 

![image](https://user-images.githubusercontent.com/7664426/206161247-281ec400-909e-43c9-b573-099380726acd.png)

Here is a screen grab from the virtual machine.

![image](https://user-images.githubusercontent.com/7664426/206161049-c0d74b2b-2638-40a3-b949-52afd4d38026.png)

I have installed same iso manually and it works. 

Please Help

**Comment by marcinbojko** [comment]
Please make sure you're able to reach that IP from outside of VM.
Especially that requires adding firewall exception which is mentioned in readme

**Comment by navanshu** [comment]
I have added the firewall exception.
I am able to ping the VM's but It is refusing to connect over SSH 

```
ssh ubuntu@192.168.1.40
```

**Comment by marcinbojko** [comment]
You cannot ssh to a machine, as it's in the Kickstart/Anaconda mode.
You have to make sure gest VM is able to contact Hyper-v you're running packer on, as packer exposes HTTP server with files for ubuntu.
Run script and check if you're able to reach port (HTTP) on IP and PORT that packer displays as used

**Comment by marcinbojko** [comment]
packer = Hyper-V host (IP:PORT) <=> VM

**Comment by navanshu** [comment]
Thanks for your support. It worked for me.

**Comment by ArchieGu** [comment]
Guys, glad you already found a solution for this issue.
Could you please let me know how to make the ssh connection work? I've add firewall exception like mentioned in the md file.

**Comment by navanshu** [comment]
If you are on windows you would need to allow connections from windows defender for the profile you have selected for the network connection. That was the issue I faced.

**Comment by ArchieGu** [comment]
这是自动回复信息。

**Comment by Souldiv** [comment]
Hey @navanshu, do you think you could guide me on how you made it work? I am unsure what you mean by allow connections from window defender, which profile is it?

**Comment by Souldiv** [comment]
Also, does it work with a default switch? when I try it with default switch it just gives me failed to unmount cd rom and gets stuck there

**Comment by navanshu** [comment]
@Souldiv  The network aka your Ethernet, etc should be marked as home or be allowed to connect both ways from the firewall and defender

**Comment by Souldiv** [comment]
@navanshu you mean the network switch? How do I do that?
