### ISSUE TITLE
WS22 - Datacenter Edition - Incorrect Value

### ISSUE THREAD

**Issue by maxwell2011** [marcinbojko/hv-packer#19]
vagrant/hv_win2022_dc.template contains an incorrect setting to define a ws22dc setup.
config.vm.define "vagrant-w2k19-dc-trial" should be w2k22-dc
config.vm.box = "w2k19-dc-trial" should be w2k22-dc

Unless I'm completely off-base here and missing something.
Otherwise, love your work. Hyper-V is a godsend compared to dealing with VMware licensing terms + pricing

**Comment by marcinbojko** [comment]
Thanks for info.
I'll mark the changes, but Vagrant is no longer support by me.

**Comment by marcinbojko** [comment]
Fixed in 3.0.1
