### ISSUE TITLE
Support for Packer Windows Update Provisioner

### ISSUE THREAD

**Issue by jwmoss** [marcinbojko/hv-packer#8]
Have you considered integrating [Packer Windows Update Provisioner](https://github.com/rgl/packer-plugin-windows-update) into your provision steps? The output of this plugin is much cleaner when ran via PowerShell vs raw output of the WU com object with PSWindowsupdate.

I'll be testing this against Windows Server 2019 DC and will report back if there are any issues.

Love the work you've done so far! Having come from a VMware shop to HyperV shop has been challenging, but your code has helped tremendously!

**Comment by marcinbojko** [comment]
Hi @jwmoss  - this is an excellent idea, however, I wanted scripts to be both usable in packer AND bare-metal construction. Thank you for your kind words - I really appreciate it.
I am not saying no to Packer, but I need to reconsider the posibilities

**Comment by jwmoss** [comment]
> Hi @jwmoss  - this is an excellent idea, however, I wanted scripts to be both usable in packer AND bare-metal construction. Thank you for your kind words - I really appreciate it.
> 
> I am not saying no to Packer, but I need to reconsider the posibilities

That makes sense! I myself use the module to manage updates as well, so I know how powerful it is.

**Comment by marcinbojko** [comment]
Your idea is an excellent, in a form I hate this repetitious task, as WU always reports different count of updates than reality says.

**Comment by marcinbojko** [comment]
It's only a year and a half , but next release should support this plugin

**Comment by marcinbojko** [comment]
Fixed by [https://github.com/marcinbojko/hv-packer/releases/tag/3.0.0](https://github.com/marcinbojko/hv-packer/releases/tag/3.0.0)
